- name: install packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
      - git
      - htop
      - iotop
      - man-db
      - manpages
      - curl
      - wget
      - gnupg

- name: symlink vi
  become: true
  ansible.builtin.file:
    src: /usr/bin/vim
    dest: /usr/bin/vi
    state: link
