- name: install apache
  apt:
    update_cache: yes
    name:
      - apache2
    state: present

- name: start and enable apache
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: yes

- name: Copy apache config file
  ansible.builtin.template:
    src: templates/apache2.conf
    dest: /etc/apache2/apache2.conf
    owner: www-data
    group: www-data
    mode: u=rw,g=r
    backup: yes
  notify: 
    - restart apache

- name: Copy SSL certificate files
  ansible.builtin.copy:
    src: files/ssl
    dest: /etc/apache2/
    owner: root
    group: root
    mode: 0644
    directory_mode:
  tags:
    - parentdir

- name: Enable modules
  community.general.apache2_module:
    name: "{{  item.module  }}"
    state: present
  loop:
    - module: ssl
    - module: headers
    - module: rewrite

- include_tasks: copy-sites.yml
